### ISSUE TITLE
Update Overhaul: after releasing Community, merge upstream into Pro

### ISSUE THREAD

**Issue by jotaen4tinypilot** [tiny-pilot/tinypilot#1028]
After we have merged the `update-overhaul` branch into `master`, we need to merge all changes upstream into Pro. Since Pro is supposed to stay on the current update mechanism, we need to revert all changes and verify that we didn’t break anything in Pro.

**Comment by jdeanwallace** [comment]
FYI @jotaen4tinypilot @mtlynch 

I have created an `update-overhaul` branch on both Pro repos and merged Community's upstream changes into it:
- https://github.com/tiny-pilot/tinypilot-pro/pull/543
- https://github.com/tiny-pilot/ansible-role-tinypilot-pro/pull/122)

Going forward, until we finally release Pro's `update-overhaul`, we'll need to change the target branch on any automatic Community PRs from `master` to `update-overhaul`. For example:

<img width="1049" alt="Screen Shot 2022-08-24 at 16 48 50" src="https://user-images.githubusercontent.com/6730025/186450284-6fba7c43-f4d8-42b7-a87c-163049acf3a9.png">

### Side note:
We could consider working on Pro's update-overhaul release from the `master` branch considering that Pro releases only happen when tagged. It might save us some mental overhead keeping track of dependent branches. 🤔

**Comment by mtlynch** [comment]
>We could consider working on Pro's update-overhaul release from the master branch considering that Pro releases only happen when tagged. It might save us some mental overhead keeping track of dependent branches. 🤔

Yeah, that was what we had in mind. I was thinking we'd need an `update-overhaul` only long enough to get rid of any Community-specific portions (e.g., changing `get-tinypilot.sh` to `get-tinypilot-pro.sh`). And then we'd just work from `master`.

The only reason we didn't do that on Community was that everything in Community refers to `master` so we can't have something incomplete in `master`. On Pro, everything refers to tagged releases. We prefer to keep Pro's `master` in a releasable state, but we don't need to keep a separation in this case because it's not worth the trouble.
