### ISSUE TITLE
Improve error messaging when updates fail due to an incorrectly set clock

### ISSUE THREAD

**Issue by cghague** [tiny-pilot/tinypilot#1503]
The TinyPilot devices don't include a built-in real-time clock, so they get the current date and time from a network time server each time they start up. This process can fail if NTP is blocked, leading to an incorrect date and time. This failure can, in turn, lead to certificate validation errors and block the update process.

We should look into ways of improving this situation, either by changing the error message when verification of a certificate's validity period fails or by trying to detect when there is a significant date mismatch between the TinyPilot device and the update server.

## Example of an existing error:

```
Error: Failed to request latest available version: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate is not yet valid (_ssl.c:1123)>
```

**Comment by mtlynch** [comment]
@cghague - Assigning this to you because I think it's a good work item to get a bit more experience with TinyPilot's Python / JS code.

I think it'd be a bit complicated to inspect the TLS cert and figure out how distant the date is from the local time. I think a good strategy here would be to catch [this particular variant of `urllib.error.URLError`](https://github.com/tiny-pilot/tinypilot/blob/0a03d2caf54aa083ef66c1606e28321f41aca781/app/version.py#L82-L84) and wrap it in an Exception that has a more actionable message for the user.
