### ISSUE TITLE
Mark items for deprioritization (Removal from this Queue)

### ISSUE THREAD

**Issue by shalver-tp** [tiny-pilot/tinypilot#1790]
Hello,

Per the Support Eng meeting on April 24, 2024.

The goal is to reduce the amount of items in the Support Eng project. Use the new status label, "Deprioritized" to mark:

- Issues that are of low impact/importance. These have generally been around for a long time and have negligible impact.

Once items are marked as deprioritized, Scott will review and move to a new project/list so that we do not completely lose them.

@db39 @cghague  Can you both weigh in?  Mark as deprioritized and add a brief comment if appropriate.

When I get to a review stage, I may ask for discussion if required.

Thanks!
Scott

**Comment by db39** [comment]
I've been a bit strict on some of these; I've marked a few tasks that have been on the backlog for over a year, even if they appear valuable. My thinking is that if they've been on the backlog for so long, they may not be as valuable as we think, they may not be use cases that we run into often, or the context in which these items first appeared may have changed.

I guess rather than "deprioritized", I've flagged these as "needs review". Happy to discuss any of them.
