### ISSUE TITLE
Use ES6 module style to enable frontend unit tests

### ISSUE THREAD

**Issue by mtlynch** [tiny-pilot/tinypilot#746]
Splitting off from https://github.com/tiny-pilot/tinypilot/issues/538#issuecomment-881484720

It would be nice if we could write unit tests for TinyPilot's frontend, which currently has no automated tests. To do this, we need to use ES6 module syntax so that we can run unit tests under Node and import our web components.

**Comment by jotaen** [comment]
Fixed via https://github.com/tiny-pilot/tinypilot-pro/pull/231.

We now have everything in place so that we can start writing unit tests in the frontend. I think good candidates to start with would be [`prettifyByteSize`](https://github.com/tiny-pilot/tinypilot-pro/blob/ca9172ce09d7162e6c4d80c8266a698e9bcca16d/app/templates/custom-elements/mass-storage-file-row.html#L194) or [`futureLocation`](https://github.com/tiny-pilot/tinypilot/blob/c6fada454409373ca5efd9d33e5dd53302a25af4/app/templates/custom-elements/change-hostname-dialog.html#L100). (We would need to extract these beforehand, of course.)

@jdeanwallace fyi, we are using ES6 modules now everywhere in the frontend. The differences in a nutshell: the `<script>` blocks are all [type “module” now](https://github.com/tiny-pilot/tinypilot/blob/c6fada454409373ca5efd9d33e5dd53302a25af4/app/templates/custom-elements/update-dialog.html#L110). That means, that all dependencies must be [imported](https://github.com/tiny-pilot/tinypilot/blob/c6fada454409373ca5efd9d33e5dd53302a25af4/app/templates/custom-elements/update-dialog.html#L122), like the controller functions or the dialog events. We don’t have the [global scripts](https://github.com/tiny-pilot/tinypilot/pull/757/files#diff-a18b3b5de30df1bcf7531723d24c214d69b2acff3cd88540e1ff186409879b0aL16) anymore, since these files have been [migrated to be modules](https://github.com/tiny-pilot/tinypilot/pull/757/files#diff-28b84268a16c05da1261418c035299ec99cc84f0dd79c3fd90c460312167b82dL11). There is also no `js/util` folder anymore, but only [one folder with all our importable JavaScript modules](https://github.com/tiny-pilot/tinypilot/tree/master/app/static/js).
