### ISSUE TITLE
Keyboard and Mouse Input Not Transmitted

### ISSUE THREAD

**Issue by lensherm** [tiny-pilot/tinypilot#751]
## Description

On a fresh install of RPi OS, the keyboard and mouse input isn't being transmitted to host

## What are the steps to reproduce this behavior?
I tried using Brave, Chrome and Safari browsers with same results.

## Logs

https://gist.github.com/mtlynch/dc7cf363a28e53ff962b401a2d4a0936

**Comment by mtlynch** [comment]
Thanks for reporting this!

What's the OS / hardware of the target computer? Does it work if you connect the TinyPilot to other computers?

What model Pi are you using and what model USB-C to USB-A cable are you using to connect the Pi to the computer?

**Comment by lensherm** [comment]
- So faI've tried connecting to a Late 2012 Mac Mini running Proxmox and to a Dell Inspiron 3880 running Windows 10, which I just pulled out of the box earlier this morning.

- In terms of the Pi, I've only tried TinyPilot with one of my Pi 4 4Gb. I have a couple more and one 8Gb. As for the cable, I am using Anker Powerline+ USB-C to USB 3.0, although I tried a couple off brands, just to be sure. I also tried with and without this thing [here](https://www.pishop.us/product/usb-c-pwr-splitter/).

**Comment by mtlynch** [comment]
I can't figure out what could be the problem here.

Usually it's one of these issues:

* USB-C to USB-A cable: unlikely, since the Anker one should work and you've tried several others
* Incompatible target computer: shouldn't be, since you've tried multiple that are known compatible
* Defective Pi: This never happens, but even if it did, you've tried multiple Pis
* Wrong OS: You're using the Raspberry Pi OS image, which is known compatible

Are you connecting directly to the Pi's USB-C port?

The last time I was this stumped, it turned out that the user was connecting through the Argon ONE case, which intercepts the USB-C port in an incompatible way.

**Comment by lensherm** [comment]
BINGO!!!!

Argon ONE strikes again. All is well in the world as soon as I connected directly!

Thank you, Mike.

**Comment by lensherm** [comment]
By the way, might want to put a DO NOT USE ARGON ONE everywhere in the documentation :-)

**Comment by michaelguild13** [comment]
@mtlynch I am having a similar issue with a target machine that's a macbook pro 2019 (monterey). I am using usb-c to usb-c for the data.
