### ISSUE TITLE
Remote screen cuts off when there is not enough vertical space

### ISSUE THREAD

**Issue by mtlynch** [tiny-pilot/tinypilot#816]
We scale down the remote screen when there's not enough horizontal space to fit it, but we don't scale for vertical space. On some laptops I've used, this causes TinyPilot to have insufficient vertical real estate to display the full remote screen in the window.

When there's not enough room to display the remote screen at full height, we should scale it down to fit.

### Current

![image](https://user-images.githubusercontent.com/7783288/142052883-f19cae1a-ad90-47c1-b0b0-2e4a2afabd10.png)

### Desired

![image](https://user-images.githubusercontent.com/7783288/142053070-71d29799-91db-4e1d-9980-0fdfa5c3e680.png)

**Comment by jotaen4tinypilot** [comment]
We have multiple very similar issues:

- https://github.com/tiny-pilot/tinypilot/issues/571 (March 11th)
- https://github.com/tiny-pilot/tinypilot/issues/797 (Sept. 29th)

My preference is still the first, not because I suggested it, but because it gives most control to the user. It’s probably enough to have these two: “Original” and “Zoom to Fit”.
