### ISSUE TITLE
Video is working, but keyboard is not working

### ISSUE THREAD

**Issue by Andre15711** [tiny-pilot/tinypilot#911]
## Description

I installed TinyPilot on my RPI3b. Video is working, but no keyboard control.

## What's the behavior that you expect?

Keyboard inputs should work.

## What's happening instead?

Noting.
The web page shows the keyboard inputs in the right lower corner, but nothing happens on the console.

## What are the steps to reproduce this behavior?

1. Open TinyPilot in Chrome
2. Click on any key on my physical or virtual keyboard.
3. nothing happens.

## Screenshots
![Bildschirmfoto 2022-02-15 um 20 31 50](https://user-images.githubusercontent.com/93643220/154135474-3e24e9ca-7cca-4aa4-9c22-8028bf8d2bbc.png)

## Logs

I also tried the command:

echo -ne "\x20\0\xb\0\0\0\0\0" > /dev/hidg0 &&   \
echo -ne "\0\0\xc\0\0\0\0\0" > /dev/hidg0 &&   \
echo -ne "\0\0\0\0\0\0\0\0" > /dev/hidg0

OUTPUT:
-bash: echo: write error: Cannot send after transport endpoint shutdown

Please paste the URL you see when you run `/opt/tinypilot/dev-scripts/dump-logs`

http://logs.tinypilotkvm.com/Vm7HWVog

**Comment by mtlynch** [comment]
Thanks for reporting this!

Unfortunately, TinyPilot requires the host hardware to have a USB port with USB OTG functionality. The Pi 3 doesn't have USB OTG, so it can't emulate USB devices, which is why you're seeing it fail to forward keystrokes.

The Pi 4B is the only officially supported hardware, but it should work on a Pi Zero W, albeit slowly.
